{
    "type": "bundle",
    "id": "bundle--d4c56d44-cb82-4e33-ab54-f2748f9bcb3c",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--6c62085c-4d08-4292-a796-8cbbf1db6156",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-04-18T00:54:15.439657Z",
            "modified": "2024-04-18T00:54:15.439657Z",
            "name": "CVE-2024-26920",
            "description": "In the Linux kernel, the following vulnerability has been resolved:\n\ntracing/trigger: Fix to return error if failed to alloc snapshot\n\nFix register_snapshot_trigger() to return error code if it failed to\nallocate a snapshot instead of 0 (success). Unless that, it will register\nsnapshot trigger without an error.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-26920"
                }
            ]
        }
    ]
}