{
    "type": "bundle",
    "id": "bundle--b85e4551-8958-44cb-aca8-5a7c46e5b1e1",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--a5b86022-5659-486e-abd5-20ba22696c4c",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-03-09T01:04:39.459763Z",
            "modified": "2025-03-09T01:04:39.459763Z",
            "name": "CVE-2023-52968",
            "description": "MariaDB Server 10.4 before 10.4.33, 10.5 before 10.5.24, 10.6 before 10.6.17, 10.7 through 10.11 before 10.11.7, 11.0 before 11.0.5, and 11.1 before 11.1.4 calls fix_fields_if_needed under mysql_derived_prepare when derived is not yet prepared, leading to a find_field_in_table crash.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2023-52968"
                }
            ]
        }
    ]
}