{
    "type": "bundle",
    "id": "bundle--7bd1ca9b-416b-4c6e-a71b-687d37e865a0",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--2b45a7c6-2af0-4460-9b03-58a5b857ef45",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-05-02T00:55:35.205063Z",
            "modified": "2024-05-02T00:55:35.205063Z",
            "name": "CVE-2024-27024",
            "description": "In the Linux kernel, the following vulnerability has been resolved:\n\nnet/rds: fix WARNING in rds_conn_connect_if_down\n\nIf connection isn't established yet, get_mr() will fail, trigger connection after\nget_mr().",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-27024"
                }
            ]
        }
    ]
}