{
    "type": "bundle",
    "id": "bundle--80efbbde-ace7-4b1f-883f-3773b11ae63b",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--8216860b-1a10-45ce-9b27-7af9ca8e150f",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-07-11T01:02:10.224093Z",
            "modified": "2024-07-11T01:02:10.224093Z",
            "name": "CVE-2024-39614",
            "description": "An issue was discovered in Django 5.0 before 5.0.7 and 4.2 before 4.2.14. get_supported_language_variant() was subject to a potential denial-of-service attack when used with very long strings containing specific characters.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-39614"
                }
            ]
        }
    ]
}