{
    "type": "bundle",
    "id": "bundle--acd5a03b-4821-4432-9161-7635f25c0477",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--bc6f21f2-cc04-488a-a2cd-aca5e0577f3b",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-02-14T01:10:51.586356Z",
            "modified": "2025-02-14T01:10:51.586356Z",
            "name": "CVE-2024-57782",
            "description": "An issue in Docker-proxy v18.09.0 allows attackers to cause a denial of service.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-57782"
                }
            ]
        }
    ]
}