{
    "type": "bundle",
    "id": "bundle--71d5fe33-64b5-4567-a965-dab8a12f3109",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--517f4dd7-aa3e-40e5-b5fd-c87b02ab664a",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-07-11T01:02:09.812638Z",
            "modified": "2024-07-11T01:02:09.812638Z",
            "name": "CVE-2024-38875",
            "description": "An issue was discovered in Django 4.2 before 4.2.14 and 5.0 before 5.0.7. urlize and urlizetrunc were subject to a potential denial of service attack via certain inputs with a very large number of brackets.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-38875"
                }
            ]
        }
    ]
}